let config;

config = {
    'Sensor #1': 'Shock Pot 1',
    'Sensor #2': 'Shock Pot 2',
    'Sensor #3': 'Shock Pot 3',
    'Sensor #4': 'Shock Pot 4',
    'Sensor #5': 'Rotor Temp 1',
    'Sensor #6': 'Rotor Temp 2',
    'Sensor #7': 'Rotor Temp 3',
    'Sensor #8': 'Rotor Temp 4',
    'Sensor #9': 'Load Cell 1',
    'Sensor #10': 'Load Cell 2',
    'Sensor #11': 'Load Cell 3',
    'Sensor #12': 'Load Cell 4',
    'Sensor #13': 'Wheel Speed 1',
    'Sensor #14': 'Wheel Speed 2',
    'Sensor #15': 'Wheel Speed 3',
    'Sensor #16': 'Wheel Speed 4',
    'Sensor #17': 'SC Pressure 1',
    'Sensor #18': 'SC Pressure 2',
    'Sensor #19': 'SC Pressure 3',
    'Sensor #20': 'SC Pressure 4',
    'Sensor #21': 'SC Pressure 5',
    'Sensor #22': 'SC Pressure 6',
    'Sensor #23': 'SC Pressure 7',
    'Sensor #24': 'SC Pressure 8',
    'Sensor #25': 'SC Pressure 9',
    'Sensor #26': 'SC Pressure 10',
    'Sensor #27': 'SC Pressure 11',
    'Sensor #28': 'SC Pressure 12',
    'Sensor #29': 'SC Pressure 13',
    'Sensor #30': 'SC Pressure 14',
    'Sensor #31': 'SC Pressure 15',
    'Sensor #32': 'SC Pressure 16',
    'Sensor #33': 'AccelX',
    'Sensor #34': 'AccelY',
    'Sensor #35': 'AccelZ',
    'Sensor #36':'Roll˙',
    'Sensor #37':'Pitch˙',
    'Sensor #38':'Yaw˙',
    'Sensor #39':'Diff Pressure',
    'Sensor #40':'Linear Pot',
    'Sensor #41':'Rotary Pot',
    'Sensor #42':'APPS',
    'Sensor #43':'SOC',
    'Sensor #44':'Current Sensor',
    'Sensor #45':'Brake Pressure',
    'Sensor #46':'Nose Pressure',
    'Sensor #47':'Gyro Roll˙',
    'Sensor #48':'Gyro Pitch˙',
    'Sensor #49':'Gyro Yaw˙',
    'Sensor #50':'Ride Height 1',
    'Sensor #51':'Ride Height 2',
    'Sensor #52':'Thermistor 1',
    'Sensor #53':'Thermistor 2',
    'Sensor #54':'Linear Pot',
    'Sensor #55':'Rotary Pot',
    'Sensor #56':'MagX',
    'Sensor #57':'MagY',
    'Sensor #58':'MagZ',
    'Sensor #59':'GPS Lat',
    'Sensor #60':'GPS Lon',
    'Sensor #61':'GPS Vn',
    'Sensor #62':'GPS Ve',
    'Sensor #63':'GPS Vd',
    'Sensor #64':'Odom V',
    'Sensor #65': 'EKF Yaw',
    'Sensor #66': 'EKF Pitch',
    'Sensor #67': 'EKF Roll',

    'Sensor #1_mapping1': 'x',
    'Sensor #2_mapping1': 'x',
    'Sensor #3_mapping1': 'x',
    'Sensor #4_mapping1': 'x',
    'Sensor #5_mapping1': 'x',
    'Sensor #6_mapping1': 'x',
    'Sensor #7_mapping1': 'x',
    'Sensor #8_mapping1': 'x',
    'Sensor #9_mapping1': 'x',
    'Sensor #10_mapping1': 'x',
    'Sensor #11_mapping1': 'x',
    'Sensor #12_mapping1': 'x',
    'Sensor #13_mapping1': 'x',
    'Sensor #14_mapping1': 'x',
    'Sensor #15_mapping1': 'x',
    'Sensor #16_mapping1': 'x',
    'Sensor #17_mapping1': 'x',
    'Sensor #18_mapping1': 'x',
    'Sensor #19_mapping1': 'x',
    'Sensor #20_mapping1': 'x',
    'Sensor #21_mapping1': 'x',
    'Sensor #22_mapping1': 'x',
    'Sensor #23_mapping1': 'x',
    'Sensor #24_mapping1': 'x',
    'Sensor #25_mapping1': 'x',
    'Sensor #26_mapping1': 'x',
    'Sensor #27_mapping1': 'x',
    'Sensor #28_mapping1': 'x',
    'Sensor #29_mapping1': 'x',
    'Sensor #30_mapping1': 'x',
    'Sensor #31_mapping1': 'x',
    'Sensor #32_mapping1': 'x',
    'Sensor #33_mapping1': 'x',
    'Sensor #34_mapping1': 'x',
    'Sensor #35_mapping1': 'x',
    'Sensor #36_mapping1': 'x',
    'Sensor #37_mapping1': 'x',
    'Sensor #38_mapping1': 'x',
    'Sensor #39_mapping1': 'x',
    'Sensor #40_mapping1': 'x',
    'Sensor #41_mapping1': 'x',
    'Sensor #42_mapping1': 'x',
    'Sensor #43_mapping1': 'x',
    'Sensor #44_mapping1': 'x',
    'Sensor #45_mapping1': 'x',
    'Sensor #46_mapping1': 'x',
    'Sensor #47_mapping1': 'x',
    'Sensor #48_mapping1': 'x',
    'Sensor #49_mapping1': 'x',
    'Sensor #50_mapping1': 'x',
    'Sensor #51_mapping1': 'x',
    'Sensor #52_mapping1': 'x',
    'Sensor #53_mapping1': 'x',
    'Sensor #54_mapping1': 'x',
    'Sensor #55_mapping1': 'x',
    'Sensor #56_mapping1': 'x',
    'Sensor #57_mapping1': 'x',
    'Sensor #58_mapping1': 'x',
    'Sensor #59_mapping1': 'x',
    'Sensor #60_mapping1': 'x',
    'Sensor #61_mapping1': 'x',
    'Sensor #62_mapping1': 'x',
    'Sensor #63_mapping1': 'x',
    'Sensor #64_mapping1': 'x',

    'Sensor #1_mapping2': 'x',
    'Sensor #2_mapping2': 'x',
    'Sensor #3_mapping2': 'x',
    'Sensor #4_mapping2': 'x',
    'Sensor #5_mapping2': 'x',
    'Sensor #6_mapping2': 'x',
    'Sensor #7_mapping2': 'x',
    'Sensor #8_mapping2': 'x',
    'Sensor #9_mapping2': 'x',
    'Sensor #10_mapping2': 'x',
    'Sensor #11_mapping2': 'x',
    'Sensor #12_mapping2': 'x',
    'Sensor #13_mapping2': 'x',
    'Sensor #14_mapping2': 'x',
    'Sensor #15_mapping2': 'x',
    'Sensor #16_mapping2': 'x',
    'Sensor #17_mapping2': 'x',
    'Sensor #18_mapping2': 'x',
    'Sensor #19_mapping2': 'x',
    'Sensor #20_mapping2': 'x',
    'Sensor #21_mapping2': 'x',
    'Sensor #22_mapping2': 'x',
    'Sensor #23_mapping2': 'x',
    'Sensor #24_mapping2': 'x',
    'Sensor #25_mapping2': 'x',
    'Sensor #26_mapping2': 'x',
    'Sensor #27_mapping2': 'x',
    'Sensor #28_mapping2': 'x',
    'Sensor #29_mapping2': 'x',
    'Sensor #30_mapping2': 'x',
    'Sensor #31_mapping2': 'x',
    'Sensor #32_mapping2': 'x',
    'Sensor #33_mapping2': 'x',
    'Sensor #34_mapping2': 'x',
    'Sensor #35_mapping2': 'x',
    'Sensor #36_mapping2': 'x',
    'Sensor #37_mapping2': 'x',
    'Sensor #38_mapping2': 'x',
    'Sensor #39_mapping2': 'x',
    'Sensor #40_mapping2': 'x',
    'Sensor #41_mapping2': 'x',
    'Sensor #42_mapping2': 'x',
    'Sensor #43_mapping2': 'x',
    'Sensor #44_mapping2': 'x',
    'Sensor #45_mapping2': 'x',
    'Sensor #46_mapping2': 'x',
    'Sensor #47_mapping2': 'x',
    'Sensor #48_mapping2': 'x',
    'Sensor #49_mapping2': 'x',
    'Sensor #50_mapping2': 'x',
    'Sensor #51_mapping2': 'x',
    'Sensor #52_mapping2': 'x',
    'Sensor #53_mapping2': 'x',
    'Sensor #54_mapping2': 'x',
    'Sensor #55_mapping2': 'x',
    'Sensor #56_mapping2': 'x',
    'Sensor #57_mapping2': 'x',
    'Sensor #58_mapping2': 'x',
    'Sensor #59_mapping2': 'x',
    'Sensor #60_mapping2': 'x',
    'Sensor #61_mapping2': 'x',
    'Sensor #62_mapping2': 'x',
    'Sensor #63_mapping2': 'x',
    'Sensor #64_mapping2': 'x',

    'Sensor #1_unit1': 'V',
    'Sensor #2_unit1': 'V',
    'Sensor #3_unit1': 'V',
    'Sensor #4_unit1': 'V',
    'Sensor #5_unit1': 'V',
    'Sensor #6_unit1': 'V',
    'Sensor #7_unit1': 'V',
    'Sensor #8_unit1': 'V',
    'Sensor #9_unit1': 'V',
    'Sensor #10_unit1': 'V',
    'Sensor #11_unit1': 'V',
    'Sensor #12_unit1': 'V',
    'Sensor #13_unit1': 'V',
    'Sensor #14_unit1': 'V',
    'Sensor #15_unit1': 'V',
    'Sensor #16_unit1': 'V',
    'Sensor #17_unit1': 'V',
    'Sensor #18_unit1': 'V',
    'Sensor #19_unit1': 'V',
    'Sensor #20_unit1': 'V',
    'Sensor #21_unit1': 'V',
    'Sensor #22_unit1': 'V',
    'Sensor #23_unit1': 'V',
    'Sensor #24_unit1': 'V',
    'Sensor #25_unit1': 'V',
    'Sensor #26_unit1': 'V',
    'Sensor #27_unit1': 'V',
    'Sensor #28_unit1': 'V',
    'Sensor #29_unit1': 'V',
    'Sensor #30_unit1': 'V',
    'Sensor #31_unit1': 'V',
    'Sensor #32_unit1': 'V',
    'Sensor #33_unit1': 'V',
    'Sensor #34_unit1': 'V',
    'Sensor #35_unit1': 'V',
    'Sensor #36_unit1': 'V',
    'Sensor #37_unit1': 'V',
    'Sensor #38_unit1': 'V',
    'Sensor #39_unit1': 'V',
    'Sensor #40_unit1': 'V',
    'Sensor #41_unit1': 'V',
    'Sensor #42_unit1': 'V',
    'Sensor #43_unit1': 'V',
    'Sensor #44_unit1': 'V',
    'Sensor #45_unit1': 'V',
    'Sensor #46_unit1': 'V',
    'Sensor #47_unit1': 'V',
    'Sensor #48_unit1': 'V',
    'Sensor #49_unit1': 'V',
    'Sensor #50_unit1': 'V',
    'Sensor #51_unit1': 'V',
    'Sensor #52_unit1': 'V',
    'Sensor #53_unit1': 'V',
    'Sensor #54_unit1': 'V',
    'Sensor #55_unit1': 'V',
    'Sensor #56_unit1': 'V',
    'Sensor #57_unit1': 'V',
    'Sensor #58_unit1': 'V',
    'Sensor #59_unit1': 'V',
    'Sensor #60_unit1': 'V',
    'Sensor #61_unit1': 'V',
    'Sensor #62_unit1': 'V',
    'Sensor #63_unit1': 'V',
    'Sensor #64_unit1': 'V',
    'Sensor #65_unit1': 'rad',
    'Sensor #66_unit1': 'rad',
    'Sensor #67_unit1': 'rad',

    'Sensor #1_unit2': 'V',
    'Sensor #2_unit2': 'V',
    'Sensor #3_unit2': 'V',
    'Sensor #4_unit2': 'V',
    'Sensor #5_unit2': 'V',
    'Sensor #6_unit2': 'V',
    'Sensor #7_unit2': 'V',
    'Sensor #8_unit2': 'V',
    'Sensor #9_unit2': 'V',
    'Sensor #10_unit2': 'V',
    'Sensor #11_unit2': 'V',
    'Sensor #12_unit2': 'V',
    'Sensor #13_unit2': 'V',
    'Sensor #14_unit2': 'V',
    'Sensor #15_unit2': 'V',
    'Sensor #16_unit2': 'V',
    'Sensor #17_unit2': 'V',
    'Sensor #18_unit2': 'V',
    'Sensor #19_unit2': 'V',
    'Sensor #20_unit2': 'V',
    'Sensor #21_unit2': 'V',
    'Sensor #22_unit2': 'V',
    'Sensor #23_unit2': 'V',
    'Sensor #24_unit2': 'V',
    'Sensor #25_unit2': 'V',
    'Sensor #26_unit2': 'V',
    'Sensor #27_unit2': 'V',
    'Sensor #28_unit2': 'V',
    'Sensor #29_unit2': 'V',
    'Sensor #30_unit2': 'V',
    'Sensor #31_unit2': 'V',
    'Sensor #32_unit2': 'V',
    'Sensor #33_unit2': 'V',
    'Sensor #34_unit2': 'V',
    'Sensor #35_unit2': 'V',
    'Sensor #36_unit2': 'V',
    'Sensor #37_unit2': 'V',
    'Sensor #38_unit2': 'V',
    'Sensor #39_unit2': 'V',
    'Sensor #40_unit2': 'V',
    'Sensor #41_unit2': 'V',
    'Sensor #42_unit2': 'V',
    'Sensor #43_unit2': 'V',
    'Sensor #44_unit2': 'V',
    'Sensor #45_unit2': 'V',
    'Sensor #46_unit2': 'V',
    'Sensor #47_unit2': 'V',
    'Sensor #48_unit2': 'V',
    'Sensor #49_unit2': 'V',
    'Sensor #50_unit2': 'V',
    'Sensor #51_unit2': 'V',
    'Sensor #52_unit2': 'V',
    'Sensor #53_unit2': 'V',
    'Sensor #54_unit2': 'V',
    'Sensor #55_unit2': 'V',
    'Sensor #56_unit2': 'V',
    'Sensor #57_unit2': 'V',
    'Sensor #58_unit2': 'V',
    'Sensor #59_unit2': 'V',
    'Sensor #60_unit2': 'V',
    'Sensor #61_unit2': 'V',
    'Sensor #62_unit2': 'V',
    'Sensor #63_unit2': 'V',
    'Sensor #64_unit2': 'V',
    'Sensor #65_unit2': 'rad',
    'Sensor #66_unit2': 'rad',
    'Sensor #67_unit2': 'rad',

    'Sensor #33': 'AccelX',
    'Sensor #34': 'AccelY',
    'Sensor #35': 'AccelZ',

    'IMU': [
        'Sensor #33',
        'Sensor #34',
        'Sensor #35',
        'Sensor #36',
        'Sensor #37',
        'Sensor #38',
        'Sensor #56',
        'Sensor #57',
        'Sensor #58',
        'Sensor #59',
        'Sensor #60',
        'Sensor #61',
        'Sensor #62',
        'Sensor #63',
        'Sensor #64',
    ],
    'Pressure': [
        'Sensor #39',
        'Sensor #17',
        'Sensor #18',
        'Sensor #19',
        'Sensor #20',
        'Sensor #21',
        'Sensor #22',
        'Sensor #23',
        'Sensor #24',
        'Sensor #25',
        'Sensor #26',
        'Sensor #27',
        'Sensor #28',
        'Sensor #29',
        'Sensor #30',
        'Sensor #31',
        'Sensor #32'
    ],
    'Ride Height': [
        'Sensor #50',
        'Sensor #51'
    ],
    'Load Cell': [
        'Sensor #9',
        'Sensor #10',
        'Sensor #11',
        'Sensor #12'
    ],
    'Nose Pressure': [
        'Sensor #46'
    ],
    'Rotor': [
        'Sensor #5',
        'Sensor #6',
        'Sensor #7',
        'Sensor #8'
    ],
    'Brake Pressure': [
        'Sensor #45'
    ],
    'Wheel Speed': [
        'Sensor #13',
        'Sensor #14',
        'Sensor #15',
        'Sensor #16'
    ],
    'APPS': [
        'Sensor #42'
    ],
    'Current Sensor': [
        'Sensor #44'
    ],
    'GPS Velocity': [
        'Sensor #61',
        'Sensor #62',
        'Sensor #63',
    ],
    'EKF Data': [
        'Sensor #65',
        'Sensor #66',
        'Sensor #67'
    ],
    'Odometer Velocity': [
        'Sensor #64'
    ],
    'SOC': [
        'Sensor #43'
    ],
    'Thermistor': [
        'Sensor #52',
        'Sensor #53',
    ],
    'Shock Pot': [
        'Sensor #1',
        'Sensor #2',
        'Sensor #3',
        'Sensor #4'
    ],
    'Steer Linear Pot': [
        'Sensor #40'
    ],
    'Steer Rotary Pot': [
        'Sensor #41'
    ]
};

module.exports = {
    config: config,
};