let config;

config = {
    'sensor_1': 'Shock Pot 1',
    'sensor_2': 'Shock Pot 2',
    'sensor_3': 'Shock Pot 3',
    'sensor_4': 'Shock Pot 4',
    'sensor_5': 'Rotor Temp 1',
    'sensor_6': 'Rotor Temp 2',
    'sensor_7': 'Rotor Temp 3',
    'sensor_8': 'Rotor Temp 4',
    'sensor_9': 'Load Cell 1',
    'sensor_10': 'Load Cell 2',
    'sensor_11': 'Load Cell 3',
    'sensor_12': 'Load Cell 4',
    'sensor_13': 'Wheel Speed 1',
    'sensor_14': 'Wheel Speed 2',
    'sensor_15': 'Wheel Speed 3',
    'sensor_16': 'Wheel Speed 4',
    'sensor_17': 'SC Pressure 1',
    'sensor_18': 'SC Pressure 2',
    'sensor_19': 'SC Pressure 3',
    'sensor_20': 'SC Pressure 4',
    'sensor_21': 'SC Pressure 5',
    'sensor_22': 'SC Pressure 6',
    'sensor_23': 'SC Pressure 7',
    'sensor_24': 'SC Pressure 8',
    'sensor_25': 'SC Pressure 9',
    'sensor_26': 'SC Pressure 10',
    'sensor_27': 'Diff Pressure',
    'sensor_28': 'Linear Pot',
    'sensor_29': 'Rotary Pot',
    'sensor_30': 'AccelX',
    'sensor_31': 'AccelY',
    'sensor_32': 'AccelZ',
    'sensor_33': 'Roll˙',
    'sensor_34': 'Pitch˙',
    'sensor_35': 'Yaw˙',

    'sensor_1_mapping1': 'x',
    'sensor_2_mapping1': 'x',
    'sensor_3_mapping1': 'x',
    'sensor_4_mapping1': 'x',
    'sensor_5_mapping1': 'x',
    'sensor_6_mapping1': 'x',
    'sensor_7_mapping1': 'x',
    'sensor_8_mapping1': 'x',
    'sensor_9_mapping1': 'x',
    'sensor_10_mapping1': 'x',
    'sensor_11_mapping1': 'x',
    'sensor_12_mapping1': 'x',
    'sensor_13_mapping1': 'x',
    'sensor_14_mapping1': 'x',
    'sensor_15_mapping1': 'x',
    'sensor_16_mapping1': 'x',
    'sensor_17_mapping1': 'x',
    'sensor_18_mapping1': 'x',
    'sensor_19_mapping1': 'x',
    'sensor_20_mapping1': 'x',
    'sensor_21_mapping1': 'x',
    'sensor_22_mapping1': 'x',
    'sensor_23_mapping1': 'x',
    'sensor_24_mapping1': 'x',
    'sensor_25_mapping1': 'x',
    'sensor_26_mapping1': 'x',
    'sensor_27_mapping1': 'x',
    'sensor_28_mapping1': 'x',
    'sensor_29_mapping1': 'x',
    'sensor_30_mapping1': 'x',
    'sensor_31_mapping1': 'x',
    'sensor_32_mapping1': 'x',
    'sensor_33_mapping1': 'x',
    'sensor_34_mapping1': 'x',
    'sensor_35_mapping1': 'x',

    'sensor_1_mapping2': 'x',
    'sensor_2_mapping2': 'x',
    'sensor_3_mapping2': 'x',
    'sensor_4_mapping2': 'x',
    'sensor_5_mapping2': 'x',
    'sensor_6_mapping2': 'x',
    'sensor_7_mapping2': 'x',
    'sensor_8_mapping2': 'x',
    'sensor_9_mapping2': 'x',
    'sensor_10_mapping2': 'x',
    'sensor_11_mapping2': 'x',
    'sensor_12_mapping2': 'x',
    'sensor_13_mapping2': 'x',
    'sensor_14_mapping2': 'x',
    'sensor_15_mapping2': 'x',
    'sensor_16_mapping2': 'x',
    'sensor_17_mapping2': 'x',
    'sensor_18_mapping2': 'x',
    'sensor_19_mapping2': 'x',
    'sensor_20_mapping2': 'x',
    'sensor_21_mapping2': 'x',
    'sensor_22_mapping2': 'x',
    'sensor_23_mapping2': 'x',
    'sensor_24_mapping2': 'x',
    'sensor_25_mapping2': 'x',
    'sensor_26_mapping2': 'x',
    'sensor_27_mapping2': 'x',
    'sensor_28_mapping2': 'x',
    'sensor_29_mapping2': 'x',
    'sensor_30_mapping2': 'x',
    'sensor_31_mapping2': 'x',
    'sensor_32_mapping2': 'x',
    'sensor_33_mapping2': 'x',
    'sensor_34_mapping2': 'x',
    'sensor_35_mapping2': 'x',

    'sensor_1_unit1': 'V',
    'sensor_2_unit1': 'V',
    'sensor_3_unit1': 'V',
    'sensor_4_unit1': 'V',
    'sensor_5_unit1': 'V',
    'sensor_6_unit1': 'V',
    'sensor_7_unit1': 'V',
    'sensor_8_unit1': 'V',
    'sensor_9_unit1': 'V',
    'sensor_10_unit1': 'V',
    'sensor_11_unit1': 'V',
    'sensor_12_unit1': 'V',
    'sensor_13_unit1': 'V',
    'sensor_14_unit1': 'V',
    'sensor_15_unit1': 'V',
    'sensor_16_unit1': 'V',
    'sensor_17_unit1': 'V',
    'sensor_18_unit1': 'V',
    'sensor_19_unit1': 'V',
    'sensor_20_unit1': 'V',
    'sensor_21_unit1': 'V',
    'sensor_22_unit1': 'V',
    'sensor_23_unit1': 'V',
    'sensor_24_unit1': 'V',
    'sensor_25_unit1': 'V',
    'sensor_26_unit1': 'V',
    'sensor_27_unit1': 'V',
    'sensor_28_unit1': 'V',
    'sensor_29_unit1': 'V',
    'sensor_30_unit1': 'V',
    'sensor_31_unit1': 'V',
    'sensor_32_unit1': 'V',
    'sensor_33_unit1': 'V',
    'sensor_34_unit1': 'V',
    'sensor_35_unit1': 'V',

    'sensor_1_unit2': 'V',
    'sensor_2_unit2': 'V',
    'sensor_3_unit2': 'V',
    'sensor_4_unit2': 'V',
    'sensor_5_unit2': 'V',
    'sensor_6_unit2': 'V',
    'sensor_7_unit2': 'V',
    'sensor_8_unit2': 'V',
    'sensor_9_unit2': 'V',
    'sensor_10_unit2': 'V',
    'sensor_11_unit2': 'V',
    'sensor_12_unit2': 'V',
    'sensor_13_unit2': 'V',
    'sensor_14_unit2': 'V',
    'sensor_15_unit2': 'V',
    'sensor_16_unit2': 'V',
    'sensor_17_unit2': 'V',
    'sensor_18_unit2': 'V',
    'sensor_19_unit2': 'V',
    'sensor_20_unit2': 'V',
    'sensor_21_unit2': 'V',
    'sensor_22_unit2': 'V',
    'sensor_23_unit2': 'V',
    'sensor_24_unit2': 'V',
    'sensor_25_unit2': 'V',
    'sensor_26_unit2': 'V',
    'sensor_27_unit2': 'V',
    'sensor_28_unit2': 'V',
    'sensor_29_unit2': 'V',
    'sensor_30_unit2': 'V',
    'sensor_31_unit2': 'V',
    'sensor_32_unit2': 'V',
    'sensor_33_unit2': 'V',
    'sensor_34_unit2': 'V',
    'sensor_35_unit2': 'V',
};

module.exports = {
    config: config,
};