let config;

config = {
    'Sensor #1': 'Shock Pot 1',
    'Sensor #2': 'Shock Pot 2',
    'Sensor #3': 'Shock Pot 3',
    'Sensor #4': 'Shock Pot 4',
    'Sensor #5': 'Rotor Temp 1',
    'Sensor #6': 'Rotor Temp 2',
    'Sensor #7': 'Rotor Temp 3',
    'Sensor #8': 'Rotor Temp 4',
    'Sensor #9': 'Load Cell 1',
    'Sensor #10': 'Load Cell 2',
    'Sensor #11': 'Load Cell 3',
    'Sensor #12': 'Load Cell 4',
    'Sensor #13': 'Wheel Speed 1',
    'Sensor #14': 'Wheel Speed 2',
    'Sensor #15': 'Wheel Speed 3',
    'Sensor #16': 'Wheel Speed 4',
    'Sensor #17': 'SC Pressure 1',
    'Sensor #18': 'SC Pressure 2',
    'Sensor #19': 'SC Pressure 3',
    'Sensor #20': 'SC Pressure 4',
    'Sensor #21': 'SC Pressure 5',
    'Sensor #22': 'SC Pressure 6',
    'Sensor #23': 'SC Pressure 7',
    'Sensor #24': 'SC Pressure 8',
    'Sensor #25': 'SC Pressure 9',
    'Sensor #26': 'SC Pressure 10',
    'Sensor #27': 'Diff Pressure',
    'Sensor #28': 'Linear Pot',
    'Sensor #29': 'Rotary Pot',
    'Sensor #30': 'AccelX',
    'Sensor #31': 'AccelY',
    'Sensor #32': 'AccelZ',
    'Sensor #33': 'Roll˙',
    'Sensor #34': 'Pitch˙',
    'Sensor #35': 'Yaw˙',

    'Sensor #1_mapping1': 'x',
    'Sensor #2_mapping1': 'x',
    'Sensor #3_mapping1': 'x',
    'Sensor #4_mapping1': 'x',
    'Sensor #5_mapping1': 'x',
    'Sensor #6_mapping1': 'x',
    'Sensor #7_mapping1': 'x',
    'Sensor #8_mapping1': 'x',
    'Sensor #9_mapping1': 'x',
    'Sensor #10_mapping1': 'x',
    'Sensor #11_mapping1': 'x',
    'Sensor #12_mapping1': 'x',
    'Sensor #13_mapping1': 'x',
    'Sensor #14_mapping1': 'x',
    'Sensor #15_mapping1': 'x',
    'Sensor #16_mapping1': 'x',
    'Sensor #17_mapping1': 'x',
    'Sensor #18_mapping1': 'x',
    'Sensor #19_mapping1': 'x',
    'Sensor #20_mapping1': 'x',
    'Sensor #21_mapping1': 'x',
    'Sensor #22_mapping1': 'x',
    'Sensor #23_mapping1': 'x',
    'Sensor #24_mapping1': 'x',
    'Sensor #25_mapping1': 'x',
    'Sensor #26_mapping1': 'x',
    'Sensor #27_mapping1': 'x',
    'Sensor #28_mapping1': 'x',
    'Sensor #29_mapping1': 'x',
    'Sensor #30_mapping1': 'x',
    'Sensor #31_mapping1': 'x',
    'Sensor #32_mapping1': 'x',
    'Sensor #33_mapping1': 'x',
    'Sensor #34_mapping1': 'x',
    'Sensor #35_mapping1': 'x',

    'Sensor #1_mapping2': 'x',
    'Sensor #2_mapping2': 'x',
    'Sensor #3_mapping2': 'x',
    'Sensor #4_mapping2': 'x',
    'Sensor #5_mapping2': 'x',
    'Sensor #6_mapping2': 'x',
    'Sensor #7_mapping2': 'x',
    'Sensor #8_mapping2': 'x',
    'Sensor #9_mapping2': 'x',
    'Sensor #10_mapping2': 'x',
    'Sensor #11_mapping2': 'x',
    'Sensor #12_mapping2': 'x',
    'Sensor #13_mapping2': 'x',
    'Sensor #14_mapping2': 'x',
    'Sensor #15_mapping2': 'x',
    'Sensor #16_mapping2': 'x',
    'Sensor #17_mapping2': 'x',
    'Sensor #18_mapping2': 'x',
    'Sensor #19_mapping2': 'x',
    'Sensor #20_mapping2': 'x',
    'Sensor #21_mapping2': 'x',
    'Sensor #22_mapping2': 'x',
    'Sensor #23_mapping2': 'x',
    'Sensor #24_mapping2': 'x',
    'Sensor #25_mapping2': 'x',
    'Sensor #26_mapping2': 'x',
    'Sensor #27_mapping2': 'x',
    'Sensor #28_mapping2': 'x',
    'Sensor #29_mapping2': 'x',
    'Sensor #30_mapping2': 'x',
    'Sensor #31_mapping2': 'x',
    'Sensor #32_mapping2': 'x',
    'Sensor #33_mapping2': 'x',
    'Sensor #34_mapping2': 'x',
    'Sensor #35_mapping2': 'x',

    'Sensor #1_unit1': 'V',
    'Sensor #2_unit1': 'V',
    'Sensor #3_unit1': 'V',
    'Sensor #4_unit1': 'V',
    'Sensor #5_unit1': 'V',
    'Sensor #6_unit1': 'V',
    'Sensor #7_unit1': 'V',
    'Sensor #8_unit1': 'V',
    'Sensor #9_unit1': 'V',
    'Sensor #10_unit1': 'V',
    'Sensor #11_unit1': 'V',
    'Sensor #12_unit1': 'V',
    'Sensor #13_unit1': 'V',
    'Sensor #14_unit1': 'V',
    'Sensor #15_unit1': 'V',
    'Sensor #16_unit1': 'V',
    'Sensor #17_unit1': 'V',
    'Sensor #18_unit1': 'V',
    'Sensor #19_unit1': 'V',
    'Sensor #20_unit1': 'V',
    'Sensor #21_unit1': 'V',
    'Sensor #22_unit1': 'V',
    'Sensor #23_unit1': 'V',
    'Sensor #24_unit1': 'V',
    'Sensor #25_unit1': 'V',
    'Sensor #26_unit1': 'V',
    'Sensor #27_unit1': 'V',
    'Sensor #28_unit1': 'V',
    'Sensor #29_unit1': 'V',
    'Sensor #30_unit1': 'V',
    'Sensor #31_unit1': 'V',
    'Sensor #32_unit1': 'V',
    'Sensor #33_unit1': 'V',
    'Sensor #34_unit1': 'V',
    'Sensor #35_unit1': 'V',

    'Sensor #1_unit2': 'V',
    'Sensor #2_unit2': 'V',
    'Sensor #3_unit2': 'V',
    'Sensor #4_unit2': 'V',
    'Sensor #5_unit2': 'V',
    'Sensor #6_unit2': 'V',
    'Sensor #7_unit2': 'V',
    'Sensor #8_unit2': 'V',
    'Sensor #9_unit2': 'V',
    'Sensor #10_unit2': 'V',
    'Sensor #11_unit2': 'V',
    'Sensor #12_unit2': 'V',
    'Sensor #13_unit2': 'V',
    'Sensor #14_unit2': 'V',
    'Sensor #15_unit2': 'V',
    'Sensor #16_unit2': 'V',
    'Sensor #17_unit2': 'V',
    'Sensor #18_unit2': 'V',
    'Sensor #19_unit2': 'V',
    'Sensor #20_unit2': 'V',
    'Sensor #21_unit2': 'V',
    'Sensor #22_unit2': 'V',
    'Sensor #23_unit2': 'V',
    'Sensor #24_unit2': 'V',
    'Sensor #25_unit2': 'V',
    'Sensor #26_unit2': 'V',
    'Sensor #27_unit2': 'V',
    'Sensor #28_unit2': 'V',
    'Sensor #29_unit2': 'V',
    'Sensor #30_unit2': 'V',
    'Sensor #31_unit2': 'V',
    'Sensor #32_unit2': 'V',
    'Sensor #33_unit2': 'V',
    'Sensor #34_unit2': 'V',
    'Sensor #35_unit2': 'V',
};

module.exports = {
    config: config,
};